site:
  title: PLAYGROUND
  start_page: component-b::index.adoc
content:
  sources:
    - url: ./docs/example-spec
    - url: ./docs/notification-spec
    - url: ./docs/search-spec
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ../antora_build
antora:
  extensions:
    - "@antora/lunr-extension"
    - ./lib/createJsonMetadata.js
